FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY sender.py .
COPY settings.py .
COPY ip_addresses.csv .

EXPOSE 1338

CMD ["gunicorn", "--bind", "0.0.0.0:1338", "--workers", "4", "--threads", "2", "sender:app"] 